```{r}

library(tidyverse)

d <- read_delim("res.csv", delim=":", 
        col_names = c("instance","tool","ncores","cores","runtime")) 

```

```{r r3, fig.height=8}

cores_order_r3 <- d %>% filter(instance=="r3") %>% arrange(ncores) %>% .[["cores"]] %>% unique

d %>% filter(instance=="r3") %>% 
  mutate(cores=factor(cores, levels=cores_order_r3)) %>% 
  ggplot() + geom_boxplot(aes(x = cores, y = runtime, color = tool)) + ylim(c(0,50)) +
  coord_flip() + facet_wrap(~ tool, ncol=1)

```

```{r}

d %>% filter(instance=="r3", tool=="h2o") %>% 
  mutate(cores=factor(cores, levels=cores_order_r3)) %>% 
  filter(!grepl(",",cores)) %>% 
  mutate(runtime_norm = runtime*ncores/min(runtime*ncores)) %>% 
  ggplot() + geom_boxplot(aes(x = cores, y = runtime_norm)) + ylim(c(0,NA))

```

```{r x1, fig.height=10}

cores_order_x1 <- d %>% filter(instance=="x1") %>% arrange(ncores) %>% .[["cores"]] %>% unique

d %>% filter(instance=="x1") %>% 
  mutate(cores=factor(cores, levels=cores_order_x1)) %>% 
  ggplot() + geom_boxplot(aes(x = cores, y = runtime, color = tool)) + ylim(c(0,50)) +
  coord_flip() + facet_wrap(~ tool, ncol=1)

```

```{r}

d %>% filter(instance=="x1", tool=="h2o") %>% 
  mutate(cores=factor(cores, levels=cores_order_x1)) %>% 
  filter(!grepl(",",cores)) %>% 
  mutate(runtime_norm = runtime*ncores/min(runtime*ncores)) %>% 
  ggplot() + geom_boxplot(aes(x = cores, y = runtime_norm)) + ylim(c(0,NA))

```


```{r h2o}

cores_order <- d %>% arrange(ncores) %>% .[["cores"]] %>% unique

d %>% filter(tool=="h2o") %>% 
  mutate(cores=factor(cores, levels=cores_order)) %>% 
  filter(!grepl(",",cores)) %>% 
  ggplot() + geom_boxplot(aes(x = cores, y = runtime, color = instance)) +
  ylim(c(0,NA)) + geom_hline(aes(yintercept = min(runtime)), color = "grey60")

```

```{r xgb}

d %>% filter(tool=="xgb") %>% 
  mutate(cores=factor(cores, levels=cores_order)) %>% 
  filter(!grepl(",",cores)) %>% 
  ggplot() + geom_boxplot(aes(x = cores, y = runtime, color = instance)) +
  ylim(c(0,60)) + geom_hline(aes(yintercept = min(runtime)), color = "grey60")

```

