```{r}

library(tidyverse)

d <- read_delim("res.csv", delim=":", 
        col_names = c("size","tool","ncores","cores","runtime")) 

```

```{r norm1_size, fig.height=10, fig.path="fig-"}

ggplot(d) + geom_boxplot(aes(x = as.factor(ncores), y = runtime/size*20, color = as.factor(size)), 
      position = position_dodge(0), width = 0.4) +
  facet_grid(tool~., scales="free") + ylim(c(0,NA)) 

```

```{r norm2_size_cores, fig.height=10, fig.path="fig-"}

ggplot(d) + geom_boxplot(aes(x = as.factor(ncores), y = runtime/size*ncores, color = as.factor(size)), 
      position = position_dodge(0), width = 0.4) +
  facet_grid(tool~., scales="free") + ylim(c(0,NA)) 

```

```{r norm3_1core, fig.height=10, fig.path="fig-"}

d %>% group_by(size, tool) %>% mutate(runtime_vs1core=runtime/first(runtime)) %>% 
  ggplot() + geom_boxplot(aes(x = as.factor(ncores), y = 1/runtime_vs1core, color = as.factor(size)), 
      position = position_dodge(0), width = 0.4) +
  facet_grid(tool~., scales="free") + ylim(c(0,NA)) 

```
